repos:
- hooks:
  - id: black
    language_version: python3.8
  repo: https://github.com/ambv/black
  rev: 21.7b0
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
- hooks:
  - id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
- hooks:
  - args:
    - --disallow-untyped-calls
    - --disallow-untyped-defs
    - --check-untyped-defs
    - --ignore-missing-import
    - --warn-unused-ignores
    - --show-error-codes
    description: Analyze Python code using Mypy
    entry: mypy
    id: mypy
    language: python
    name: mypy
    stages:
    - commit
    types:
    - python
  repo: local
# - hooks:
#   - id: python-safety-dependencies-check
#   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#   rev: v1.2.1
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: master
