name: run_tests

on:
  push:
    branch:
      - 'main'

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install latest pip, build, twine
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade build twine
      - name: Install dependencies
        run: |
          python -m pip install .[dev]
      - name: Run tests
        run: |
          pytest
